### ISSUE TITLE
Links don't work!

### ISSUE THREAD

**Issue by Andis59** [DVaughan/MarkdownMonster-Addin-TocGenerator#5]
I have just installed you TocGenerator adding and it works fine, except that the links don't work.
I have follow your note about removing base from head in the preview template I'm using, but nothing changes.

I'm not a HTML guru, but to get '`<a href="#foo">foo</a>'` to work you need to have an id="foo" on the element that we should jump to, e.g. "`<h1 id="foo">Foo </h1>`"

If I look at the html code that is produced, by Markdown Monster, there is no id's!

I have autolinks=true

I'm running Markdown Monster 1.8.1 and TocGenerator 1.1

What have I done wrong?
// Anders

**Comment by DVaughan** [comment]
Hi Anders,

This isn't an issue with the TOC Generator. Are you certain you have "MarkdownOptions": {
    "AutoLinks": true

Are you using the default Markdown parser?

Regards,
Daniel

**Comment by Andis59** [comment]
This is a snippet from the settings 
```
"MarkdownOptions": {
    "AutoLinks": true,
    "Abbreviations": true,
    "AutoHeaderIdentifiers": false,
    "StripYamlFrontMatter": true,
    "EmojiAndSmiley": true,
    "MediaLinks": true,
    "ListExtras": true,
    "Figures": true,
    "GithubTaskLists": true,
    "SmartyPants": false,
    "RenderLinksAsExternal": false,
    "MarkdigExtensions": "emphasisextras,pipetables,gridtables,footers,footnotes,citations,attributes",
    "AllowRenderScriptTags": false,
    "MarkdownParserName": "MarkDig"
  },
```
I have only installed the Markdown Monster via its installation program and then added your Toc Generator via the Addin Manager.

**Comment by DVaughan** [comment]
I don't know. You may want to ask @RickStrahl

**Comment by Andis59** [comment]
OK! Thanks for TocGenerator and for your answers!
// Anders

**Comment by RickStrahl** [comment]
You need to set `AutoHeaderIdentifiers: true` in the file for auto-link creation to work not `AutoLinks`.

MM has logic in it to internally navigate hash links and there is in fact an issue in that it navigates to anchors, not ID tags. I've fixed this with:

```js
            if (hash) {                
                var sel = hash + "[name='" + hash.substr(1) + "'],#"+ hash.substr(1);                                          
                var $el = $(sel);                
                $("html").scrollTop($el.offset().top - 100);
                return false;
            }
```

in `preview.js`. This should make the links work in the inline browser and exports, but not in `View in Web Browser` due to the requirement of the `base` tag to pull in resources. The base tag will make `#` hashes navigate based on that the base rather than document related links which is something I didn't even realize.

Exported files don't include a base tag, so hashes behave `normally`.

There is another issue here though:

* The link mappings don't match what Markdig produces

Specifically the way punctuation is handled is different. Here are a few things that don't translate right:

* NET Core 2.0 and ASP.NET Core 2.0 - The Promised Land?
* 2.0 Versions of .NET Core and .NET Standard bring back many .NET APIs

My recommendation is that instead of relying on the #Ids, explicitly create anchor tags into the document just before the headers.

**Comment by DVaughan** [comment]
Ah yes, it's *AutoHeaderIdentifiers* not *AutoLinks*. Hopefully that will do it, Anders.

Rick, I've replaced the link generation logic with that which Markdig uses. Hopefully that will eliminate the punctuation issue. I agree that generating anchors would be better.

**Comment by RickStrahl** [comment]
Can you rebuild the addin and update the version number so the update shows up in the addin registry?

**Comment by DVaughan** [comment]
Done. I meant to do that last night.
